-- =========================================================================
-- APEX -- Bibliotheque d'exercices du coach (204 exercices avec video)
-- A executer dans Supabase > SQL Editor (apres training_module.sql)
-- =========================================================================

DELETE FROM exercices_bdd WHERE youtube_url IS NULL;

INSERT INTO exercices_bdd (nom, muscle_principal, equipement, type_effort, youtube_url) VALUES
  ('Lat Pulldown PRONATION', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=tJ6HBRlHQRY&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=3&t=0s'),
  ('Câble face pull', 'dos', 'cables', 'reps', 'https://youtube.com/shorts/ZSP_kGDJ8kw?feature=share'),
  ('Lat Pulldown NEUTRE', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=oiILPQyizuk&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=5&t=0s'),
  ('Reverse pec deck câble', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=6z7PwWBusc8&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=22&t=0s'),
  ('Elévations frontales aux haltères', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/-BEOLoeczgs?feature=share'),
  ('French Press à la corde', 'triceps', 'cables', 'reps', 'https://youtube.com/shorts/eWeqCXGYqYI?feature=share'),
  ('Crossover câble bas (semi pronation)', 'pectoraux', 'cables', 'reps', 'https://youtube.com/shorts/SQOHew4wZ5c?feature=share'),
  ('Gironda Row', 'dos', 'cables', 'reps', 'https://youtube.com/shorts/ZDVzj4d5VvY?feature=share'),
  ('Standing Curl aux haltères (supination)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/uo6FGeUqGxU?feature=share'),
  ('Développé militaire aux haltères (prise neutre)', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/WpjmLGiIQ80?feature=share'),
  ('Inclined 60° Crossover câble haut', 'pectoraux', 'cables', 'reps', 'https://www.youtube.com/watch?v=dxXoKt20l74'),
  ('Lat Pulldown SUPINATION', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=Vu433oHrxrI&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=4&t=0s'),
  ('Spider Curl 30° aux haltères (supination)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/YThsaecGtIg?feature=share'),
  ('half kneeling shoulder press', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/6DQBA3W1bWs?feature=share'),
  ('Chest Press Machine', 'pectoraux', 'machine', 'reps', 'https://youtube.com/shorts/E7fl51PkEn4?si=8Uxp-V3S64ixklyA'),
  ('Lat Pulldown 1 bras', 'dos', 'cables', 'reps', 'https://youtube.com/shorts/7ghN8DWOuLY?feature=share'),
  ('Curl Incliné 30° aux haltères (supination)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/NGggPjLsJtI?feature=share'),
  ('Alternating Shoulder Press', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/dQTKer3uHCs?feature=share'),
  ('Inclined Câble chest press', 'pectoraux', 'cables', 'reps', 'https://www.youtube.com/shorts/N_dJChcrxgQ'),
  ('Straight Arm Pulldown', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=LCRtFTS0KNY&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=7&t=0s'),
  ('DBs Upright Row', 'epaules', 'halteres', 'reps', 'https://www.youtube.com/watch?v=fy-Ou88ruAk&pp=ygUPREJzIHVwcmlnaHQgcm93'),
  ('Scott Curl aux haltères (supination)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/y5clRs-UBto?feature=share'),
  ('Reverse Pec Deck Machine', 'dos', 'machine', 'reps', 'https://www.youtube.com/watch?v=DbRwz_exJk8&pp=ygUYcmV2ZXJzZSBwZWMgZGVjayBtYWNoaW5l'),
  ('Scott Curl machine', 'biceps', 'machine', 'reps', 'https://www.youtube.com/shorts/DNl5kTWHNhk'),
  ('Crossover câble milieu (neutre)', 'pectoraux', 'cables', 'reps', 'https://youtube.com/shorts/4mPfjIiKXNg?feature=share'),
  ('Seated Row SUPINATION', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=J_DcdS8VX1U&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=17&t=0s'),
  ('Mid cable Seated one arm flyes', 'pectoraux', 'cables', 'reps', 'https://youtube.com/shorts/HdejVB6Iq9s?feature=share'),
  ('Seated Row PRONATION to chest', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=Mj5dxLNNcV4&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=16&t=0s'),
  ('Flyes au câble bas', 'pectoraux', 'cables', 'reps', 'https://www.youtube.com/watch?v=em_EfuiqR4g'),
  ('Seated Row NEUTRE', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=BP4rDj5c_P8&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=18&t=0s'),
  ('Peck deck machine', 'pectoraux', 'machine', 'reps', 'https://www.youtube.com/watch?v=O-OBCfyh9Fw&pp=ygURcGVjayBkZWNrIG1hY2hpbmU%3D'),
  ('Seated Row NEUTRE bent over', 'dos', 'cables', 'reps', 'https://www.youtube.com/watch?v=HqbTOJF3nIU&list=PL5p-4I4xmZUeiTVNm5guPrK7Y6zR450-j&index=19&t=0s'),
  ('EZ Bar Curl', 'biceps', 'barre', 'reps', 'https://youtube.com/shorts/X8naLUsoVGM'),
  ('Elévations frontales à la EZ Bar', 'epaules', 'barre', 'reps', 'https://youtube.com/shorts/pfh4oBkRuEY?feature=share'),
  ('EZ Bar Scott Curl', 'biceps', 'barre', 'reps', 'https://youtube.com/shorts/R8X9T3KcteM?feature=share'),
  ('Landmine Press', 'epaules', 'barre', 'reps', 'https://youtube.com/shorts/gztN_taowkk?feature=share'),
  ('Développé militaire à la barre', 'epaules', 'barre', 'reps', 'https://youtube.com/shorts/ZyQyWPAxjb0?feature=share'),
  ('In line Triceps extension 1 bras', 'triceps', 'cables', 'reps', 'https://youtube.com/shorts/dy84UmsGRvI?feature=share'),
  ('EZ Bar Upright row', 'epaules', 'barre', 'reps', 'https://www.youtube.com/watch?v=Na9OlsqQ5Zs&pp=ygUSRVogQmFyIHVwcmlnaHQgcm93'),
  ('Triceps extension à la corde', 'triceps', 'cables', 'reps', 'https://youtube.com/shorts/4hWnBEwf43I?feature=share'),
  ('Low câble curl avec barre courte', 'biceps', 'cables', 'reps', 'https://www.youtube.com/shorts/Tr6ZHq2OQmk'),
  ('Triceps kick back à la poulie', 'triceps', 'cables', 'reps', 'https://youtube.com/shorts/rdYlKe3PJRU?feature=share'),
  ('Crossover câble haut', 'pectoraux', 'cables', 'reps', 'https://youtube.com/shorts/4Ge46tA5ll0?feature=share'),
  ('In line Curl supination', 'biceps', 'cables', 'reps', 'https://youtube.com/shorts/KfMV_9_7VKQ?feature=share'),
  ('Low Cable Behind Body Curl Supination (coudes serrés)', 'biceps', 'cables', 'reps', 'https://youtube.com/shorts/_el8jRYZ4fI?feature=share'),
  ('Traction Supination', 'biceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/Z8bKoHWwctM?feature=share'),
  ('Tirage buste penché aux haltères (lats focus)', 'dos', 'halteres', 'reps', 'https://youtube.com/shorts/Z_uddp5xLGc?feature=share'),
  ('Tirage buste penché aux haltères (semi pronation)', 'dos', 'halteres', 'reps', 'https://youtube.com/shorts/Z_uddp5xLGc?feature=share'),
  ('Tirage bûcheron (lats focus)', 'dos', 'halteres', 'reps', 'https://youtube.com/shorts/KbYylMlnXzQ?feature=share'),
  ('Elevations latérales aux haltères', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/PJNyNfqVVOQ?feature=share'),
  ('Triceps Extension couché aux haltères', 'triceps', 'halteres', 'reps', 'https://youtube.com/shorts/gdhHm743tWs?feature=share'),
  ('Flyes aux haltères', 'pectoraux', 'halteres', 'reps', 'https://youtube.com/shorts/Jx7CffuJXWM?feature=share'),
  ('Tirage bûcheron coude ouvert', 'dos', 'halteres', 'reps', 'https://youtube.com/shorts/v0mIYfuTzZo?feature=share'),
  ('Standing Curl aux haltères (neutre)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/xfYTKvNHxSo'),
  ('Elevations latérales incliné 30° aux haltères', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/vX_DsjlV7BI?feature=share'),
  ('Triceps Extension incliné 30° aux haltères', 'triceps', 'halteres', 'reps', 'https://youtube.com/shorts/njaw8MAoSVA?feature=share'),
  ('Flyes décliné aux haltères', 'pectoraux', 'halteres', 'reps', 'https://youtube.com/shorts/Mdqv5HUj_k0?feature=share'),
  ('Flyes inversés', 'dos', 'halteres', 'reps', 'https://youtube.com/shorts/U00vcf15Sdw?feature=share'),
  ('Spider Curl aux haltères (neutre)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/4FnUb9JgfQI?feature=share'),
  ('Elevations latérales incliné 45° aux haltères', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/aWpth5VqMow?feature=share'),
  ('French Press aux haltères', 'triceps', 'halteres', 'reps', 'https://youtube.com/shorts/LoKhlFbGmeM?feature=share'),
  ('Flyes incliné 30° aux haltères', 'pectoraux', 'halteres', 'reps', 'https://youtube.com/shorts/GHyCaG737w0?feature=share'),
  ('Chest supported 30° Flyes inversés', 'dos', 'halteres', 'reps', 'https://youtube.com/shorts/zo3xDP0GQTg?feature=share'),
  ('Curl Incliné 30° aux haltères (neutre)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/dvJA31sFKI8?feature=share'),
  ('Elevations latérales incliné 60° aux haltères', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/f7x5C1-n0JU?feature=share'),
  ('Pull Over à l''haltère', 'triceps', 'halteres', 'reps', 'https://youtube.com/shorts/Gkp7a8i-azk?feature=share'),
  ('Shrugs aux haltères', 'dos', 'halteres', 'reps', 'https://youtube.com/shorts/k1fl1rddXWg?feature=share'),
  ('Poliquin Lateral Raises', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/Qcq5b0UfCeE?feature=share'),
  ('Chest supported 30° Shrugs aux haltères', 'dos', 'halteres', 'reps', 'https://youtube.com/shorts/fl5y0CNO9Ls?feature=share'),
  ('Scott Curl aux haltères (neutre)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/5PE93MNg2nw?feature=share'),
  ('Elevations en Y incliné 45°', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/_S21SpvLZt8?feature=share'),
  ('Floor Press aux haltères', 'triceps', 'halteres', 'reps', 'https://youtube.com/shorts/Mwp2w5oCNy8?feature=share'),
  ('Développé couché aux haltères', 'pectoraux', 'halteres', 'reps', 'https://youtube.com/shorts/tzaq0nARp3o?feature=share'),
  ('Chest supported  DBs Row', 'dos', 'halteres', 'reps', 'https://youtu.be/VfluQyN2_ek?si=Kin--bRq1gmB8UlH'),
  ('Alternating Floor Press aux haltères', 'triceps', 'halteres', 'reps', 'https://youtube.com/shorts/WFCMDaAbpRk?feature=share'),
  ('Développé incliné aux haltères', 'pectoraux', 'halteres', 'reps', 'https://youtube.com/shorts/_y7yDomtUPY?feature=share'),
  ('Gorilla row', 'dos', 'autres', 'reps', 'https://youtu.be/ljzLtsz63YM?si=zm9ET8E2PDpMyeHG'),
  ('Développé décliné aux haltères', 'pectoraux', 'halteres', 'reps', 'https://youtube.com/shorts/hEnJ0ffHnE4?feature=share'),
  ('Low Cable One arm latéral raise', 'epaules', 'cables', 'reps', 'https://youtube.com/shorts/0ah88g7Ocpc?feature=share'),
  ('Low Cable Rope Curl (coudes milieu)', 'biceps', 'cables', 'reps', 'https://youtube.com/shorts/9VDX1HRFxKo?feature=share'),
  ('Lateral Deltoid Machine', 'epaules', 'machine', 'reps', 'https://www.youtube.com/shorts/bB_FNepte6A'),
  ('Low Cable Rope Curl OFFSET', 'biceps', 'cables', 'reps', 'https://youtube.com/shorts/CLjoQZMC4Mg?feature=share'),
  ('Tirage buste penché à la barre (pronation)', 'dos', 'barre', 'reps', 'https://youtube.com/shorts/JRo976ODwoU'),
  ('Tirage buste penché à la barre (supination)', 'dos', 'barre', 'reps', 'https://youtube.com/shorts/fv_wyn6eBGY?feature=share'),
  ('Flyes inversés (prise neutre)', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/sWstzWbnX7A?feature=share'),
  ('Pendlay Row', 'dos', 'barre', 'reps', 'https://youtube.com/shorts/KtJQiPRFbGk?feature=share'),
  ('Standing Curl aux haltères (offset)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/FnCTPWF5qjI?feature=share'),
  ('Cobra Press', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/i1jIDd8fD60?feature=share'),
  ('Spider Curl aux haltères (offset)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/Qv0iR8L1kDQ?feature=share'),
  ('Rotation externe à l''haltère', 'epaules', 'halteres', 'reps', 'https://youtube.com/shorts/ma3msD3qJL4?feature=share'),
  ('EZ Bar French Press', 'triceps', 'barre', 'reps', 'https://youtube.com/shorts/bT6YPweUasw?feature=share'),
  ('Landmine Row', 'dos', 'barre', 'reps', 'https://youtube.com/shorts/9WZwvL7sJbs?si=XK-_jA8TZdjMeKIr'),
  ('Curl Incliné 30° aux haltères (offset)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/tjsZFIvMEJY?feature=share'),
  ('Seated Rear delt raises (pronation)', 'epaules', 'halteres', 'reps', 'https://youtu.be/MMgl5ZtN278?si=myjYNlGuLpMrDXDR'),
  ('EZ Bar Pull Over', 'triceps', 'barre', 'reps', 'https://youtube.com/shorts/UneZbbVaSjs?feature=share'),
  ('Mid Cable Rotation Externe (coude serré)', 'epaules', 'cables', 'reps', 'https://youtube.com/shorts/oR3S3NdZ5Rc?feature=share'),
  ('High Cable Curl OffSet bras écartés', 'biceps', 'cables', 'reps', 'https://www.youtube.com/watch?v=Ulhnn0de3I0&list=PL5p-4I4xmZUfeOVAakrNyBSOZvJkYtk2A&index=17'),
  ('Mid Cable Rotation Externe (coude haut)', 'epaules', 'cables', 'reps', 'https://youtube.com/shorts/W0NlHddXodc?feature=share'),
  ('Traction Pronation', 'dos', 'poids_corps', 'reps', 'https://youtube.com/shorts/h4zDg-kc9bU?feature=share'),
  ('Pompes', 'pectoraux', 'poids_corps', 'reps', 'https://youtube.com/shorts/KpWJ7iS9mlY?feature=share'),
  ('Dips machine assistance', 'triceps', 'machine', 'reps', 'https://www.youtube.com/shorts/-Ztmc6d5AXY'),
  ('Pompes incliné', 'pectoraux', 'poids_corps', 'reps', 'https://youtube.com/shorts/pPepcSHzT98?feature=share'),
  ('Pronation Biceps Curl aux haltères', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/tsALjIBnygg?feature=share'),
  ('Dips machine', 'triceps', 'machine', 'reps', 'https://www.youtube.com/shorts/vBAcMMW8bMA'),
  ('Pompes en déficit', 'pectoraux', 'poids_corps', 'reps', 'https://youtube.com/shorts/ajxtmv-PYdg?feature=share'),
  ('Zottman Curl aux haltères (Pronation)', 'biceps', 'halteres', 'reps', 'https://youtube.com/shorts/inOPTcIbgJk?feature=share'),
  ('Pronation EZ Bar Curl', 'biceps', 'barre', 'reps', 'https://youtube.com/shorts/QayYz6fnaV8?feature=share'),
  ('Single leg bent knee calf raise', 'mollets', 'poids_corps', 'reps', 'https://youtube.com/shorts/cNfTqm87-54?si=AaJh0XxIHZ81_QjO'),
  ('Leg Press wide stance', 'quadriceps', 'machine', 'reps', 'https://www.youtube.com/shorts/g_xCTJ4jlLA'),
  ('Leg curl assis', 'ischio', 'machine', 'reps', 'https://www.youtube.com/watch?v=_qwLdYywo_A&pp=ygUPc2VhdGVkIGxlZyBjdXJs'),
  ('Leg Extension', 'quadriceps', 'machine', 'reps', 'https://www.youtube.com/shorts/LxJauFBzJ0Q'),
  ('Leg curl allongé', 'ischio', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=LxI-ec8cQYo'),
  ('Hack Squat Machine', 'quadriceps', 'machine', 'reps', 'https://youtube.com/shorts/y3nJdbFb3Ng?si=h2qrEVhIbgdq3BBR'),
  ('Fentes arrières avec haltères', 'fessiers', 'halteres', 'reps', 'https://youtube.com/shorts/E6tX02Fh4WU?feature=share'),
  ('Good morning', 'ischio', 'barre', 'reps', 'https://youtube.com/shorts/ujpNDWC3Zu8?feature=share'),
  ('Romanian Deadlift', 'fessiers', 'barre', 'reps', 'https://youtube.com/shorts/6h2-tzPkkeY'),
  ('Romanian Deadlift sur 1 jambe', 'fessiers', 'barre', 'reps', 'https://youtube.com/shorts/xKaREP8gLsE'),
  ('Goblet Squat', 'quadriceps', 'halteres', 'reps', 'https://youtube.com/shorts/XAYKo__uLqU?feature=share'),
  ('KB Swing', 'fessiers', 'autres', 'reps', 'https://youtube.com/shorts/eZ6xZSKbmFo'),
  ('Cyclist Goblet Squat', 'quadriceps', 'halteres', 'reps', 'https://youtube.com/shorts/Ue2nudWIc8I?feature=share'),
  ('KB Swing vs band', 'fessiers', 'autres', 'reps', 'https://youtube.com/shorts/u_u3tNrVDYY'),
  ('Déficit Sumo squat avec haltère', 'quadriceps', 'halteres', 'reps', 'https://youtube.com/shorts/gcysp2shek4?feature=share'),
  ('Curtsy fentes à la barre', 'fessiers', 'barre', 'reps', 'https://youtu.be/msvF1e9w2aQ?si=adCN37lFitGudMOP'),
  ('Double haltères front rack squat', 'quadriceps', 'halteres', 'reps', 'https://youtube.com/shorts/YK0_bhUJepE?feature=share'),
  ('Rower Leg curl', 'ischio', 'machine', 'reps', 'https://youtube.com/shorts/tb7Sa-jNTFo?feature=share'),
  ('Foam Roll Hack Squat aux haltères', 'quadriceps', 'halteres', 'reps', 'https://youtube.com/shorts/vXrBsZwxh3U?feature=share'),
  ('Single leg chinese plank', 'ischio', 'poids_corps', 'temps', 'https://youtu.be/bpwvgvbp-Ig?si=OghzA_PxAiMvKL55'),
  ('Bulgarian Split squat', 'quadriceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/iQRmtvq_oDA?feature=share'),
  ('Back Squat', 'fessiers', 'barre', 'reps', 'https://youtube.com/shorts/1czyTobSte4?feature=share'),
  ('Box Squat', 'fessiers', 'barre', 'reps', 'https://youtube.com/shorts/RlGkI9vaGjo?feature=share'),
  ('Fente arrière', 'fessiers', 'poids_corps', 'reps', 'https://www.youtube.com/shorts/OnLG0Tv9LBU'),
  ('Deficit Romanian Deadlift', 'fessiers', 'barre', 'reps', 'https://youtu.be/QvS-zXFinLw?si=z_VzMqz32Ip1x7kC'),
  ('Abductor machine', 'ischio', 'machine', 'reps', 'https://youtube.com/shorts/TL73RTLTY9g?si=GpufuCdfDl9pLEdY'),
  ('Adductor Machine', 'ischio', 'machine', 'reps', 'https://youtube.com/shorts/eYA6y_ZnrDQ?si=K_Y7hu79HjPFhH5h'),
  ('double rebond de face', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=HiK1zRyIwag&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=3'),
  ('Front squat', 'quadriceps', 'barre', 'reps', 'https://youtube.com/shorts/eZAqU1im0yk?feature=share'),
  ('Low câble glute extension', 'fessiers', 'cables', 'reps', 'https://youtube.com/shorts/u6-uBJnTR14?feature=share'),
  ('Bond + stabilisation de face', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=oqgqMFy-5sw&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=12'),
  ('Cyclist Front Squat', 'quadriceps', 'barre', 'reps', 'https://youtube.com/shorts/1qzE3-pxrzU?feature=share'),
  ('Rope Pull through', 'fessiers', 'cables', 'reps', 'https://youtube.com/shorts/H3q6dcfu_NY?feature=share'),
  ('Bond enchaînés de face', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=uuBpWAULrqc&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=14'),
  ('Bond + stabilisation latérale', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=6WecKDvSHkc&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=13'),
  ('double rebond de face 1 jambe', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=mOVzlm4UnUg&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=4'),
  ('Bond + stabilisation 1 jambe', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=LbTK7s__2Yw&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=17'),
  ('Fentes', 'fessiers', 'poids_corps', 'reps', 'https://youtube.com/shorts/cOzHtan1Wtc'),
  ('Bond enchaînés de face 1 jambe', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=ZeWbXiWI2iU&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=18'),
  ('Squat au poids du corps', 'quadriceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/gp9RByMsxJg?feature=share'),
  ('Fentes alternés', 'fessiers', 'poids_corps', 'reps', 'https://youtube.com/shorts/uIZh7yEwrqA'),
  ('double rebond latéral 1 jambe', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=REmkVE0hK-8&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=2'),
  ('Fentes statique + Dynamique', 'fessiers', 'poids_corps', 'reps', 'https://youtube.com/shorts/MeqM4sBpy20'),
  ('Bond Patineur', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=bQ6FjQ0v1no&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=15'),
  ('Glute Bridge', 'fessiers', 'poids_corps', 'reps', 'https://youtube.com/shorts/_N0ljKF2eg4?feature=share'),
  ('Bond latéraux enchaînés 1 pied', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=syW9E4vxMQI&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=11'),
  ('Front toes step up', 'quadriceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/cB5jPmMplug?feature=share'),
  ('Glute Bridge Unilatéral', 'fessiers', 'poids_corps', 'reps', 'https://youtube.com/shorts/F-6-YhRd0Go'),
  ('Bond patineur en avançant', 'mollets', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=yl-AJYSCEa0&list=PL5p-4I4xmZUeT0XqLYoGYba-WbnSi_kod&index=16'),
  ('Front Step up', 'quadriceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/CzGO46SXEfM?feature=share'),
  ('45° Back Extension', 'fessiers', 'machine', 'reps', 'https://youtube.com/shorts/CLRoxz4mkXo?si=YTkqSYhU31gR36if'),
  ('Glute extension machine', 'fessiers', 'machine', 'reps', 'https://www.youtube.com/watch?v=BwpXq6dpgR0&pp=ygUXZ2x1dGUgZXh0ZW5zaW9uIG1hY2hpbmU%3D'),
  ('Low câble glute abduction', 'fessiers', 'cables', 'reps', 'https://youtube.com/shorts/AU6B1pCWwLg?feature=share'),
  ('Cossack Squat', 'fessiers', 'poids_corps', 'reps', 'https://youtube.com/shorts/mQPvzd0kX5g'),
  ('Goblet Cossack Squat', 'fessiers', 'halteres', 'reps', 'https://youtube.com/shorts/iiwdxTJrEWI'),
  ('Low lateral Step up', 'quadriceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/ay4NYzICzMI?feature=share'),
  ('Lateral Step up', 'quadriceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/twrX0CMYdGI?feature=share'),
  ('Fentes alternées', 'quadriceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/uIZh7yEwrqA?feature=share'),
  ('Fentes stato dynamique', 'quadriceps', 'poids_corps', 'reps', 'https://youtube.com/shorts/MeqM4sBpy20?feature=share'),
  ('Front plank', 'abdos', 'poids_corps', 'temps', 'https://youtube.com/shorts/hvIcEUEeUAQ?si=bgRCDWAL86PXyAap'),
  ('Abmat sit ups', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/o08gSFhxybs?feature=share'),
  ('Tuck up', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/6k-Jxs6pBDk?feature=share'),
  ('V up', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/--J_U3jOBrI?feature=share'),
  ('DRagon flag', 'abdos', 'poids_corps', 'reps', 'https://youtu.be/qW1KX9uWESw?si=9RMDix6ZzJRIl7lk'),
  ('GHD Back extension snatch grip', 'abdos', 'machine', 'reps', 'https://youtu.be/ZQYEB20GLtc?si=Mn3hqaMj0pOfJgVJ'),
  ('Tuck DRagon flag', 'abdos', 'poids_corps', 'reps', 'https://youtu.be/ip9aegcVPas?si=xNvoaNaK7dYn16dy'),
  ('GHD Back extension focus fessiers', 'abdos', 'machine', 'reps', 'https://youtube.com/shorts/birBZKkJNbs?feature=share'),
  ('Hollow hold', 'abdos', 'poids_corps', 'temps', 'https://youtube.com/shorts/Qzmn3mQIuuQ?feature=share'),
  ('Hollow flutter kicks', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/D1tWpIfoLC0?feature=share'),
  ('Hollow rock', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/lQrhPy4-mVE?feature=share'),
  ('Leg raises', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/DDma0FaSw0s?feature=share'),
  ('Reverse crunch banc incliné 30°', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/eY-QKTuKDsg?feature=share'),
  ('Hollow leg raises', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/jB8yBDcpPXY?feature=share'),
  ('Hollow crunch', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/LZjkc7HYAmM?feature=share'),
  ('Strict Hanging Knee raises', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/91yHl7VMdsE?feature=share'),
  ('Strict Hanging Knee to elbow', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/M7V2JIHCsAQ?feature=share'),
  ('Garhammer raises', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/CTR_hYHQLdw?si=UtMSDvROrwcYdjfm'),
  ('Strict Hanging Leg raises', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/I4AYawTepDM?feature=share'),
  ('L sit', 'abdos', 'poids_corps', 'temps', 'https://youtube.com/shorts/yB8cQSq9whc?feature=share'),
  ('Strict Toes to bar', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/fQYKwUig9mU?feature=share'),
  ('LATERAL GHD HOLD', 'abdos', 'machine', 'temps', 'https://youtube.com/shorts/1qFrvIZEYME?si=od6_UbJiYJWz1UHL'),
  ('NECK PLANK', 'abdos', 'poids_corps', 'temps', 'https://youtube.com/shorts/FDrjQ36lMaU?si=yjp7WUx-9rKWlvfq'),
  ('Dead Bug', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/_IJiWSd8VM0?feature=share'),
  ('Dead bug vs MB', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/LZmCvZ8AgQM?feature=share'),
  ('Crunch machine', 'abdos', 'machine', 'reps', 'https://www.youtube.com/shorts/z5m6eKKRJQc'),
  ('Half ghd sit ups', 'abdos', 'machine', 'reps', 'https://youtube.com/shorts/kYzN9jqZx6U?si=KG1fKcU4wlTGC0Gx'),
  ('DB Side Bend', 'abdos', 'halteres', 'reps', 'https://youtube.com/shorts/08yvJFBgk70?feature=share'),
  ('Dynamic Lateral plank', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/UYBKvf2YWtw?feature=share'),
  ('Lateral Leg raises', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/BjE5zP9S8vY?feature=share'),
  ('Copenhagen plank', 'abdos', 'poids_corps', 'temps', 'https://youtube.com/shorts/dC5g-x6iM0A?feature=share'),
  ('Dynamic Copenhagen plank', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/tIMhgCkNHsg?feature=share'),
  ('Low cable Side Bend', 'abdos', 'cables', 'reps', 'https://youtube.com/shorts/hkTyOiwQh5U?feature=share'),
  ('Russian Twist', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/codv-pSqQwM?feature=share'),
  ('V up croisée', 'abdos', 'poids_corps', 'reps', 'https://www.youtube.com/watch?v=RUvCDib3uUk&pp=ygUMViBVUCBDUk9JUzJF'),
  ('half kneeling palof press', 'abdos', 'poids_corps', 'reps', 'https://youtube.com/shorts/2dFk0F6pwsE?si=301uUusp6kfEcXUF'),
  ('Star plank', 'abdos', 'poids_corps', 'temps', 'https://youtube.com/shorts/fcq5CLp25Lg?si=OI0QlrFvM7l0axPN'),
  ('Single Arm Farmer''s Carry', 'abdos', 'autres', 'distance', 'https://youtu.be/6npFKmvhmas?si=sM5-_xQI-kkR1voZ')
ON CONFLICT DO NOTHING;