-- APEX — Import RUGBY WORK Phases 1 à 10 (généré depuis l'Excel)
-- Exercices issus des fiches vidéo. Idempotent. Supabase > SQL Editor.

-- 1) Exercices absents
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Développé couché aux haltères','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Développé couché aux haltères');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Lat Pulldown NEUTRE','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Lat Pulldown NEUTRE');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Fente arrière','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Fente arrière');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Elevations latérales incliné 60° aux haltères','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Elevations latérales incliné 60° aux haltères');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Gorilla row','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Gorilla row');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Seated Row NEUTRE','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Seated Row NEUTRE');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Hack Squat Machine','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Hack Squat Machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Romanian Deadlift','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Romanian Deadlift');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Développé militaire aux haltères (prise neutre)','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Développé militaire aux haltères (prise neutre)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Low câble curl avec barre courte','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Low câble curl avec barre courte');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'DB Side Bend','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='DB Side Bend');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Crossover câble haut','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Crossover câble haut');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Tirage bûcheron (lats focus)','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Tirage bûcheron (lats focus)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Leg Extension','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Leg Extension');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Elévations frontales aux haltères','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Elévations frontales aux haltères');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Triceps extension à la corde','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Triceps extension à la corde');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT '45° Back Extension','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='45° Back Extension');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Alternating Shoulder Press','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Alternating Shoulder Press');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Standing Curl aux haltères (offset)','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Standing Curl aux haltères (offset)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'LATERAL GHD HOLD','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='LATERAL GHD HOLD');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'NECK PLANK','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='NECK PLANK');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Lat Pulldown PRONATION','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Lat Pulldown PRONATION');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Peck deck machine','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Peck deck machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'DRagon flag','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='DRagon flag');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Crossover câble milieu (neutre)','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Crossover câble milieu (neutre)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Câble face pull','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Câble face pull');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Back Squat','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Back Squat');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Traction Pronation','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Traction Pronation');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Développé militaire à la barre','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Développé militaire à la barre');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Tirage buste penché à la barre (pronation)','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Tirage buste penché à la barre (pronation)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Barbell bent over row','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Barbell bent over row');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Elevations latérales aux haltères','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Elevations latérales aux haltères');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Triceps Extension couché aux haltères','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Triceps Extension couché aux haltères');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Flyes inversés (prise neutre)','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Flyes inversés (prise neutre)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Hollow leg raises','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Hollow leg raises');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Bulgarian Split squat','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Bulgarian Split squat');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Flyes aux haltères','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Flyes aux haltères');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'EZ Bar Scott Curl','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='EZ Bar Scott Curl');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'abdos à la roulette','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='abdos à la roulette');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Développé couché à la barre','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Développé couché à la barre');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Landmine Press','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Landmine Press');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'SA GHD Hip extension','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='SA GHD Hip extension');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'French Press à la corde','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='French Press à la corde');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Single Arm Farmer''s Carry','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Single Arm Farmer''s Carry');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Plyo push ups','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Plyo push ups');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'DC VS BAND','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='DC VS BAND');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Plyo push ups banded assisted','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Plyo push ups banded assisted');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Squat jump','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Squat jump');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Speed sled push','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Speed sled push');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Band Assisted squat jump','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Band Assisted squat jump');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Développé incliné aux haltères','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Développé incliné aux haltères');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Romanian Deadlift sur 1 jambe','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Romanian Deadlift sur 1 jambe');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Tirage buste penché aux haltères (lats focus)','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Tirage buste penché aux haltères (lats focus)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Leg curl assis','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Leg curl assis');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'DBs Upright Row','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='DBs Upright Row');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Triceps extension en X','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Triceps extension en X');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Chest Press Machine','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Chest Press Machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Lateral Deltoid Machine','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Lateral Deltoid Machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Curl Incliné 30° aux haltères (offset)','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Curl Incliné 30° aux haltères (offset)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'V up','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='V up');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Développé couché','autre','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Développé couché');

-- 2) Programmes
DO $$
DECLARE v_coach UUID; v_tpl UUID; v_seance UUID;
BEGIN
  SELECT id INTO v_coach FROM profiles WHERE role='coach' ORDER BY created_at LIMIT 1;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 1' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 1',4,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé couché aux haltères' LIMIT 1),0,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat Pulldown NEUTRE' LIMIT 1),1,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Fente arrière' LIMIT 1),2,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Elevations latérales incliné 60° aux haltères' LIMIT 1),3,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Gorilla row' LIMIT 1),4,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row NEUTRE' LIMIT 1),0,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hack Squat Machine' LIMIT 1),1,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),2,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé militaire aux haltères (prise neutre)' LIMIT 1),3,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble curl avec barre courte' LIMIT 1),4,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DB Side Bend' LIMIT 1),5,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Crossover câble haut' LIMIT 1),0,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Tirage bûcheron (lats focus)' LIMIT 1),1,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg Extension' LIMIT 1),2,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Elévations frontales aux haltères' LIMIT 1),3,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension à la corde' LIMIT 1),4,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='45° Back Extension' LIMIT 1),5,'amrap',1,'5:00',180,NULL,'Max de reps en 5min · 40-60 reps · 3min');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 2' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 2',5,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé couché aux haltères' LIMIT 1),0,'reps',3,'12-15',120,'A','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Tirage bûcheron (lats focus)' LIMIT 1),1,'reps',3,'12-15',120,'A','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),2,'reps',3,'12-15',120,'B','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Alternating Shoulder Press' LIMIT 1),3,'reps',3,'12-15',120,'B','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Standing Curl aux haltères (offset)' LIMIT 1),4,'reps',3,'12-15',120,'C','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension à la corde' LIMIT 1),5,'reps',3,'12-15',120,'C','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='LATERAL GHD HOLD' LIMIT 1),6,'reps',3,'—',120,'D','3-4 supersets · 10-20sec / côté Exercice 1 · 20-40sec Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='NECK PLANK' LIMIT 1),7,'reps',3,'—',120,'D','3-4 supersets · 10-20sec / côté Exercice 1 · 20-40sec Exercice 2 · 2min');
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé militaire aux haltères (prise neutre)' LIMIT 1),0,'reps',3,'12-15',120,'A','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat Pulldown PRONATION' LIMIT 1),1,'reps',3,'12-15',120,'A','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Peck deck machine' LIMIT 1),2,'reps',3,'12-15',120,'B','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Elevations latérales incliné 60° aux haltères' LIMIT 1),3,'reps',3,'12-15',120,'B','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble curl avec barre courte' LIMIT 1),4,'reps',3,'12-15',120,'C','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension à la corde' LIMIT 1),5,'reps',3,'12-15',120,'C','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DRagon flag' LIMIT 1),6,'reps',3,'12-15',120,'D','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DB Side Bend' LIMIT 1),7,'reps',3,'12-15',120,'D','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Crossover câble milieu (neutre)' LIMIT 1),0,'reps',3,'12-15',120,'A','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Tirage bûcheron (lats focus)' LIMIT 1),1,'reps',3,'12-15',120,'A','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),2,'reps',3,'12-15',120,'B','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg Extension' LIMIT 1),3,'reps',3,'12-15',120,'B','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Elévations frontales aux haltères' LIMIT 1),4,'reps',3,'12-15',120,'C','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble face pull' LIMIT 1),5,'reps',3,'12-15',120,'C','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 3' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 3',5,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back Squat' LIMIT 1),0,'reps',3,'12',120,NULL,'Up to 8RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Traction Pronation' LIMIT 1),1,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé militaire à la barre' LIMIT 1),2,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Tirage buste penché à la barre (pronation)' LIMIT 1),3,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Barbell bent over row' LIMIT 1),0,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),1,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Elevations latérales aux haltères' LIMIT 1),2,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps Extension couché aux haltères' LIMIT 1),3,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Flyes inversés (prise neutre)' LIMIT 1),4,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hollow leg raises' LIMIT 1),5,'reps',3,'—',120,NULL,'abdos ·');
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé militaire à la barre' LIMIT 1),0,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Bulgarian Split squat' LIMIT 1),1,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Tirage bûcheron (lats focus)' LIMIT 1),2,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Flyes aux haltères' LIMIT 1),3,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='EZ Bar Scott Curl' LIMIT 1),4,'reps',3,'12',120,NULL,'Up to 12RM · back off set 10% · 3 sets of 12 reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='abdos à la roulette' LIMIT 1),5,'reps',3,'—',120,NULL,'abdos à la roulette ·');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 4' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 4',6,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé couché à la barre' LIMIT 1),0,'reps',2,'3',2,NULL,'Up to 3RM pause 2sec (for strength) · then -20% · 2sets of 3reps pause 2sec (for speed)');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back Squat' LIMIT 1),1,'reps',2,'3',2,NULL,'Up to 3RM pause 2sec (for strength) · then -20% · 2sets of 3reps pause 2sec (for speed)');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Landmine Press' LIMIT 1),2,'reps',3,'Max',120,'A','3sets · max reps Exercice 1 · max reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='SA GHD Hip extension' LIMIT 1),3,'reps',3,'Max',120,'A','3sets · max reps Exercice 1 · max reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='French Press à la corde' LIMIT 1),4,'reps',3,'12-15',120,'B','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Standing Curl aux haltères (offset)' LIMIT 1),5,'reps',3,'12-15',120,'B','3-4 supersets · 12-15 reps Exercice 1 · 12-15 reps Exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Single Arm Farmer''s Carry' LIMIT 1),6,'reps',3,'—',120,'C','45m /côté à accumuler');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 5' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 5',6,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Plyo push ups' LIMIT 1),0,'reps',3,'—',120,'A','3 séries de 3 répétition par exercice · Développé Couché à la barre à 80% · Développé couché vs band · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DC VS BAND' LIMIT 1),1,'reps',3,'—',120,'A','3 séries de 3 répétition par exercice · Développé Couché à la barre à 80% · Développé couché vs band · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Plyo push ups banded assisted' LIMIT 1),2,'reps',3,'—',120,'A','3 séries de 3 répétition par exercice · Développé Couché à la barre à 80% · Développé couché vs band · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back Squat' LIMIT 1),3,'reps',3,'—',120,'B','3 séries de 3 répétition par exercice · Back Squat à 80% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Squat jump' LIMIT 1),4,'reps',3,'—',120,'B','3 séries de 3 répétition par exercice · Back Squat à 80% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Speed sled push' LIMIT 1),5,'reps',3,'—',120,'B','3 séries de 3 répétition par exercice · Back Squat à 80% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Band Assisted squat jump' LIMIT 1),6,'reps',3,'—',120,'B','3 séries de 3 répétition par exercice · Back Squat à 80% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé incliné aux haltères' LIMIT 1),7,'reps',3,'32',120,'C','3 supersets · Accumuler 32 reps sur l''exercice 1 · Accumuler 32 reps sur l''exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift sur 1 jambe' LIMIT 1),8,'reps',3,'32',120,'C','3 supersets · Accumuler 32 reps sur l''exercice 1 · Accumuler 32 reps sur l''exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Tirage buste penché aux haltères (lats focus)' LIMIT 1),9,'reps',3,'32',120,'D','3 supersets · Accumuler 32 reps sur l''exercice 1 · Accumuler 32 reps sur l''exercice 2 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Elevations latérales incliné 60° aux haltères' LIMIT 1),10,'reps',3,'32',120,'D','3 supersets · Accumuler 32 reps sur l''exercice 1 · Accumuler 32 reps sur l''exercice 2 · 2min');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 6' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 6',4,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé couché aux haltères' LIMIT 1),0,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hack Squat Machine' LIMIT 1),1,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),2,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DBs Upright Row' LIMIT 1),3,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='45° Back Extension' LIMIT 1),4,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row NEUTRE' LIMIT 1),0,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),1,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Crossover câble haut' LIMIT 1),2,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension en X' LIMIT 1),3,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble curl avec barre courte' LIMIT 1),4,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Chest Press Machine' LIMIT 1),0,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Fente arrière' LIMIT 1),1,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Flyes inversés (prise neutre)' LIMIT 1),2,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lateral Deltoid Machine' LIMIT 1),3,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Curl Incliné 30° aux haltères (offset)' LIMIT 1),4,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='V up' LIMIT 1),5,'reps',3,'Max',120,NULL,'3 sets of max reps · 2min');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 7' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 7',6,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé couché à la barre' LIMIT 1),0,'reps',4,'3',120,NULL,'4 sets of 3 reps à 60% vs bands or chains · up to 3 reps heavy but speed without bands');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hack Squat Machine' LIMIT 1),1,'reps',4,'2',120,NULL,'4 sets of 2 reps à 60% vs bands or chains · up to 3 reps heavy but speed without bands');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row NEUTRE' LIMIT 1),2,'reps',4,'2',120,'A','4 sets of 2 reps à 60% vs bands or chains · up to 3 reps heavy but speed without bands');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',4,'2',120,'A','4 sets of 2 reps à 60% vs bands or chains · up to 3 reps heavy but speed without bands');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='French Press à la corde' LIMIT 1),4,'reps',4,'2',120,'B','4 sets of 2 reps à 60% vs bands or chains · up to 3 reps heavy but speed without bands');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Standing Curl aux haltères (offset)' LIMIT 1),5,'reps',4,'2',120,'B','4 sets of 2 reps à 60% vs bands or chains · up to 3 reps heavy but speed without bands');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back Squat' LIMIT 1),6,'reps',4,'2',120,'C','4 sets of 2 reps à 60% vs bands or chains · up to 3 reps heavy but speed without bands');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 8' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 8',6,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé couché à la barre' LIMIT 1),0,'reps',5,'5',120,NULL,'5 sets of 5 reps deficit plyometrics push ups · up to 3 reps heavy but speed pause bench');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hack Squat Machine' LIMIT 1),1,'reps',5,'3',120,NULL,'5 sets of 3 reps barbell squat jump à 20kg · up to 3 reps heavy but speed squat pause');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row NEUTRE' LIMIT 1),2,'reps',5,'3',120,'A','5 sets of 3 reps barbell squat jump à 20kg · up to 3 reps heavy but speed squat pause');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',5,'3',120,'A','5 sets of 3 reps barbell squat jump à 20kg · up to 3 reps heavy but speed squat pause');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='French Press à la corde' LIMIT 1),4,'reps',5,'3',120,'B','5 sets of 3 reps barbell squat jump à 20kg · up to 3 reps heavy but speed squat pause');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Standing Curl aux haltères (offset)' LIMIT 1),5,'reps',5,'3',120,'B','5 sets of 3 reps barbell squat jump à 20kg · up to 3 reps heavy but speed squat pause');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back Squat' LIMIT 1),6,'reps',5,'3',120,'C','5 sets of 3 reps barbell squat jump à 20kg · up to 3 reps heavy but speed squat pause');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 9' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 9',6,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé couché' LIMIT 1),0,'reps',3,'1-3',120,NULL,'3 séries · 1-3 reps à 85% · 3 Xplosive reps à 55% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hack Squat Machine' LIMIT 1),1,'reps',3,'1-3',120,NULL,'3 séries · 1-3 reps à 85% · 2 Xplosive reps à 55% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row NEUTRE' LIMIT 1),2,'reps',3,'1-3',120,'A','3 séries · 1-3 reps à 85% · 2 Xplosive reps à 55% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',3,'1-3',120,'A','3 séries · 1-3 reps à 85% · 2 Xplosive reps à 55% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='French Press à la corde' LIMIT 1),4,'reps',3,'1-3',120,'B','3 séries · 1-3 reps à 85% · 2 Xplosive reps à 55% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Standing Curl aux haltères (offset)' LIMIT 1),5,'reps',3,'1-3',120,'B','3 séries · 1-3 reps à 85% · 2 Xplosive reps à 55% · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back Squat' LIMIT 1),6,'reps',3,'1-3',120,'C','3 séries · 1-3 reps à 85% · 2 Xplosive reps à 55% · 2min');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='RUGBY WORK Phase 10' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'RUGBY WORK Phase 10',6,'men',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Développé couché' LIMIT 1),0,'reps',4,'3',120,NULL,'4 séries · 3 reps à 50% · tempo X2X1 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hack Squat Machine' LIMIT 1),1,'reps',6,'2',120,NULL,'6 séries · 2 reps à 50% · tempo X2X1 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row NEUTRE' LIMIT 1),2,'reps',6,'2',120,'A','6 séries · 2 reps à 50% · tempo X2X1 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',6,'2',120,'A','6 séries · 2 reps à 50% · tempo X2X1 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='French Press à la corde' LIMIT 1),4,'reps',6,'2',120,'B','6 séries · 2 reps à 50% · tempo X2X1 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Standing Curl aux haltères (offset)' LIMIT 1),5,'reps',6,'2',120,'B','6 séries · 2 reps à 50% · tempo X2X1 · 2min');
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, superset_groupe, notes) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back Squat' LIMIT 1),6,'reps',6,'2',120,'C','6 séries · 2 reps à 50% · tempo X2X1 · 2min');
  END IF;
END $$;