-- =========================================================================
-- APEX — Import WOMEN WORK Phases 2 à 10 (généré depuis l'Excel)
-- À lancer dans Supabase > SQL Editor. Idempotent (re-lançable sans doublon).
-- =========================================================================

-- 1) Créer les exercices manquants (par nom, sans doublon)
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Back squat','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Back squat');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'One leg hip trust','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='One leg hip trust');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Low câble gironda row','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Low câble gironda row');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Curtsy lunges','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Curtsy lunges');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Low câble glute abduction','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Low câble glute abduction');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Triceps extension corde','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Triceps extension corde');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Lateral GHD Sit ups','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Lateral GHD Sit ups');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Fentes arrières aux haltères','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Fentes arrières aux haltères');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Romanian Deadlift','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Romanian Deadlift');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'DBs Flyes','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='DBs Flyes');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Leg extension machine','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Leg extension machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Câble adducteurs','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Câble adducteurs');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'One arm Row','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='One arm Row');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Star plank','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Star plank');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Deficit Sumo Squat','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Deficit Sumo Squat');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Back extension','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Back extension');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Lat pulldown pronation','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Lat pulldown pronation');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Leg curl assis','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Leg curl assis');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Glute extension machine','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Glute extension machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'lateral raises','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='lateral raises');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Garhammer raises','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Garhammer raises');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'ATG Squat','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='ATG Squat');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Hip trust','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Hip trust');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Seated Row','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Seated Row');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Back extension (glute focus)','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Back extension (glute focus)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'GHD Sit ups','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='GHD Sit ups');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Bulgarian split squat','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Bulgarian split squat');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Deficit Romanian Deadlift','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Deficit Romanian Deadlift');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Chest Press','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Chest Press');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'ADDuctor machine','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='ADDuctor machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'ABDuctor machine','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='ABDuctor machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Reverse Peck Deck machine','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Reverse Peck Deck machine');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Dynamic Copenhagen plank','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Dynamic Copenhagen plank');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Deficit Sumo DB Squat','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Deficit Sumo DB Squat');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'One leg Romanian Deadlift','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='One leg Romanian Deadlift');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Lat pulldown supination','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Lat pulldown supination');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Dragon flag','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Dragon flag');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Foam roll squat','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Foam roll squat');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Hip dominant Step up (rack assisted)','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Hip dominant Step up (rack assisted)');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Câble glute kick back','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Câble glute kick back');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Hollow hold + V up','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Hollow hold + V up');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Step up','jambes','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Step up');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'DBs bent over row','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='DBs bent over row');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Static + Dynamic Copenhagen plank','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Static + Dynamic Copenhagen plank');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Triceps french press','haut du corps','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Triceps french press');
INSERT INTO exercices_bdd (nom, muscle_principal, type_effort) SELECT 'Front plank (coudes au sol et pieds sur le rameur)','abdos','reps' WHERE NOT EXISTS (SELECT 1 FROM exercices_bdd WHERE nom='Front plank (coudes au sol et pieds sur le rameur)');

-- 2) Créer les programmes (un par phase) avec séances et exercices
DO $$
DECLARE v_coach UUID; v_tpl UUID; v_seance UUID;
BEGIN
  SELECT id INTO v_coach FROM profiles WHERE role='coach' ORDER BY created_at LIMIT 1;

  -- ===== WOMEN WORK Phase 2 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 2' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 2',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back squat' LIMIT 1),0,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One leg hip trust' LIMIT 1),1,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble gironda row' LIMIT 1),2,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Curtsy lunges' LIMIT 1),3,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble glute abduction' LIMIT 1),4,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension corde' LIMIT 1),5,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lateral GHD Sit ups' LIMIT 1),6,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Fentes arrières aux haltères' LIMIT 1),0,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),1,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DBs Flyes' LIMIT 1),2,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg extension machine' LIMIT 1),3,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble adducteurs' LIMIT 1),4,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One arm Row' LIMIT 1),5,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Star plank' LIMIT 1),6,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Deficit Sumo Squat' LIMIT 1),0,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension' LIMIT 1),1,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown pronation' LIMIT 1),2,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Glute extension machine' LIMIT 1),4,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Garhammer raises' LIMIT 1),6,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"10","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
  END IF;

  -- ===== WOMEN WORK Phase 3 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 3' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 3',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='ATG Squat' LIMIT 1),0,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hip trust' LIMIT 1),1,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row' LIMIT 1),2,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension (glute focus)' LIMIT 1),4,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='GHD Sit ups' LIMIT 1),6,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Bulgarian split squat' LIMIT 1),0,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Deficit Romanian Deadlift' LIMIT 1),1,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Chest Press' LIMIT 1),2,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='ADDuctor machine' LIMIT 1),3,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='ABDuctor machine' LIMIT 1),4,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Reverse Peck Deck machine' LIMIT 1),5,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Dynamic Copenhagen plank' LIMIT 1),6,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Deficit Sumo DB Squat' LIMIT 1),0,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One leg Romanian Deadlift' LIMIT 1),1,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown supination' LIMIT 1),2,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg extension machine' LIMIT 1),3,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension corde' LIMIT 1),4,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 brûlant en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Dragon flag' LIMIT 1),5,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 brûlant en position basse',NULL,NULL);
  END IF;

  -- ===== WOMEN WORK Phase 4 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 4' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 4',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Foam roll squat' LIMIT 1),0,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hip trust' LIMIT 1),1,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble gironda row' LIMIT 1),2,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hip dominant Step up (rack assisted)' LIMIT 1),3,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble glute kick back' LIMIT 1),4,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension corde' LIMIT 1),5,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='GHD Sit ups' LIMIT 1),6,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Bulgarian split squat' LIMIT 1),0,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),1,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DBs Flyes' LIMIT 1),2,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble glute abduction' LIMIT 1),4,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One arm Row' LIMIT 1),5,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Dynamic Copenhagen plank' LIMIT 1),6,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back squat' LIMIT 1),0,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension (glute focus)' LIMIT 1),1,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown pronation' LIMIT 1),2,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Fentes arrières aux haltères' LIMIT 1),3,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble adducteurs' LIMIT 1),4,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Dragon flag' LIMIT 1),6,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Rest-pause — 10RM puis max reps après 15-20s','Max (rest-pause)',18);
  END IF;

  -- ===== WOMEN WORK Phase 5 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 5' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 5',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back squat' LIMIT 1),0,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One leg hip trust' LIMIT 1),1,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble gironda row' LIMIT 1),2,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Curtsy lunges' LIMIT 1),3,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble glute abduction' LIMIT 1),4,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension corde' LIMIT 1),5,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lateral GHD Sit ups' LIMIT 1),6,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Fentes arrières aux haltères' LIMIT 1),0,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),1,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DBs Flyes' LIMIT 1),2,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg extension machine' LIMIT 1),3,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble adducteurs' LIMIT 1),4,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One arm Row' LIMIT 1),5,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Star plank' LIMIT 1),6,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Deficit Sumo Squat' LIMIT 1),0,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension' LIMIT 1),1,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown pronation' LIMIT 1),2,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Glute extension machine' LIMIT 1),4,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Garhammer raises' LIMIT 1),6,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"4","charge":""},{"reps":"6","charge":""},{"reps":"8","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
  END IF;

  -- ===== WOMEN WORK Phase 6 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 6' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 6',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='ATG Squat' LIMIT 1),0,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hip trust' LIMIT 1),1,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row' LIMIT 1),2,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension (glute focus)' LIMIT 1),4,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='GHD Sit ups' LIMIT 1),6,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Bulgarian split squat' LIMIT 1),0,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Deficit Romanian Deadlift' LIMIT 1),1,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Chest Press' LIMIT 1),2,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='ADDuctor machine' LIMIT 1),3,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='ABDuctor machine' LIMIT 1),4,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Reverse Peck Deck machine' LIMIT 1),5,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Dynamic Copenhagen plank' LIMIT 1),6,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Deficit Sumo DB Squat' LIMIT 1),0,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One leg Romanian Deadlift' LIMIT 1),1,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown supination' LIMIT 1),2,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg extension machine' LIMIT 1),3,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension corde' LIMIT 1),4,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Dragon flag' LIMIT 1),5,'reps',3,'8-12',120,'[{"reps":"8-12","charge":""},{"reps":"8-12","charge":""},{"reps":"8-12","charge":""}]'::jsonb,'EXTRA. 1 & 1/4 en position basse',NULL,NULL);
  END IF;

  -- ===== WOMEN WORK Phase 7 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 7' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 7',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Foam roll squat' LIMIT 1),0,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hip trust' LIMIT 1),1,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble gironda row' LIMIT 1),2,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hip dominant Step up (rack assisted)' LIMIT 1),3,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble glute kick back' LIMIT 1),4,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension corde' LIMIT 1),5,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='GHD Sit ups' LIMIT 1),6,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Bulgarian split squat' LIMIT 1),0,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),1,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DBs Flyes' LIMIT 1),2,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble glute abduction' LIMIT 1),4,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One arm Row' LIMIT 1),5,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Dynamic Copenhagen plank' LIMIT 1),6,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back squat' LIMIT 1),0,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension (glute focus)' LIMIT 1),1,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown pronation' LIMIT 1),2,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Fentes arrières aux haltères' LIMIT 1),3,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble adducteurs' LIMIT 1),4,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Dragon flag' LIMIT 1),6,'reps',3,'Max',180,'[{"reps":"Max","charge":""},{"reps":"Max","charge":""},{"reps":"Max","charge":""}]'::jsonb,'EXTRA. Double drop set 70-80% / 60% / 50%','Drop 60% → 50%',15);
  END IF;

  -- ===== WOMEN WORK Phase 8 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 8' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 8',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back squat' LIMIT 1),0,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One leg hip trust' LIMIT 1),1,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble gironda row' LIMIT 1),2,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Curtsy lunges' LIMIT 1),3,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble glute abduction' LIMIT 1),4,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension corde' LIMIT 1),5,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lateral GHD Sit ups' LIMIT 1),6,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Fentes arrières aux haltères' LIMIT 1),0,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),1,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DBs Flyes' LIMIT 1),2,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg extension machine' LIMIT 1),3,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble adducteurs' LIMIT 1),4,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One arm Row' LIMIT 1),5,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Star plank' LIMIT 1),6,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Deficit Sumo Squat' LIMIT 1),0,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension' LIMIT 1),1,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown pronation' LIMIT 1),2,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Glute extension machine' LIMIT 1),4,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,NULL,NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Garhammer raises' LIMIT 1),6,'reps',4,'12',120,'[{"reps":"12","charge":""},{"reps":"10","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""}]'::jsonb,'EXTRA. ',NULL,NULL);
  END IF;

  -- ===== WOMEN WORK Phase 9 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 9' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 9',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back squat' LIMIT 1),0,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hip trust' LIMIT 1),1,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Seated Row' LIMIT 1),2,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble glute kick back' LIMIT 1),4,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'EXTRA. Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Hollow hold + V up' LIMIT 1),6,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'EXTRA. Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Step up' LIMIT 1),0,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension' LIMIT 1),1,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Chest Press' LIMIT 1),2,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='ABDuctor machine' LIMIT 1),3,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DBs bent over row' LIMIT 1),4,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'EXTRA. Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Static + Dynamic Copenhagen plank' LIMIT 1),5,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'EXTRA. Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown supination' LIMIT 1),0,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One leg Romanian Deadlift' LIMIT 1),1,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='ADDuctor machine' LIMIT 1),2,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg extension machine' LIMIT 1),3,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps french press' LIMIT 1),4,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'EXTRA. Iso en position basse',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Front plank (coudes au sol et pieds sur le rameur)' LIMIT 1),5,'reps',3,'5" iso +5',150,'[{"reps":"5\" iso +5","charge":""},{"reps":"4\" iso +4","charge":""},{"reps":"3\" iso +3","charge":""}]'::jsonb,'EXTRA. Iso en position basse',NULL,NULL);
  END IF;

  -- ===== WOMEN WORK Phase 10 =====
  IF NOT EXISTS (SELECT 1 FROM prog_templates WHERE nom='WOMEN WORK Phase 10' AND coach_id=v_coach) THEN
    INSERT INTO prog_templates (coach_id, nom, nb_semaines, tag, actif) VALUES (v_coach,'WOMEN WORK Phase 10',3,'women',true) RETURNING id INTO v_tpl;
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 1',1,0) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back squat' LIMIT 1),0,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One leg hip trust' LIMIT 1),1,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble gironda row' LIMIT 1),2,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Curtsy lunges' LIMIT 1),3,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Low câble glute abduction' LIMIT 1),4,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Triceps extension corde' LIMIT 1),5,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'EXTRA. Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lateral GHD Sit ups' LIMIT 1),6,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'EXTRA. Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 2',2,1) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Fentes arrières aux haltères' LIMIT 1),0,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Romanian Deadlift' LIMIT 1),1,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='DBs Flyes' LIMIT 1),2,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg extension machine' LIMIT 1),3,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Câble adducteurs' LIMIT 1),4,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='One arm Row' LIMIT 1),5,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'EXTRA. Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Star plank' LIMIT 1),6,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'EXTRA. Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_seances (template_id, nom, jour, ordre) VALUES (v_tpl,'Séance 3',3,2) RETURNING id INTO v_seance;
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Deficit Sumo Squat' LIMIT 1),0,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Back extension' LIMIT 1),1,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Lat pulldown pronation' LIMIT 1),2,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Leg curl assis' LIMIT 1),3,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Glute extension machine' LIMIT 1),4,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='lateral raises' LIMIT 1),5,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'EXTRA. Plus lourd sur la 2e vague',NULL,NULL);
    INSERT INTO prog_template_exercices (seance_id, exercice_id, ordre, type_effort, series, reps_cible, repos_secondes, series_data, notes, reps_secondaire, repos_intra_sec) VALUES (v_seance,(SELECT id FROM exercices_bdd WHERE nom='Garhammer raises' LIMIT 1),6,'reps',6,'8',180,'[{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""},{"reps":"8","charge":""},{"reps":"6","charge":""},{"reps":"4","charge":""}]'::jsonb,'EXTRA. Plus lourd sur la 2e vague',NULL,NULL);
  END IF;
END $$;

-- 3) Diagnostic : exercices sans vidéo (à enrichir ensuite si besoin)
SELECT nom, muscle_principal FROM exercices_bdd WHERE youtube_url IS NULL ORDER BY nom;